name: plugin_pjmei_components
description: A new Flutter plugin project.
version: 0.0.130
homepage:

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  web_socket_channel: ^2.4.3
  animations: ^2.0.7
  app_settings: ^5.1.1
  audioplayers: ^6.0.0
  barcode_widget: ^2.0.4
  barcode: ^2.2.4
  bot_toast: ^4.1.1
  brasil_fields: ^1.14.0
  cached_network_image: ^3.2.3
  chewie: ^1.7.1
  cloud_firestore: ^4.8.0
  connectivity_plus: ^6.0.1
  crop: ^0.5.4
  crypto: ^3.0.3
  dartz: ^0.10.1
  device_info_plus: ^10.0.1
  dio: ^5.2.0
  dot_navigation_bar: ^1.0.1+4
  dotted_border: ^2.0.0+3
  dynamic_color: ^1.6.6
  emoji_picker_flutter: ^2.0.0
  encrypt: ^5.0.1
  equatable: ^2.0.5
  eva_icons_flutter: ^3.1.0
  extended_image: ^8.0.0
  extended_image_library: ^4.0.2
  extended_masked_text: ^2.3.1
  file_picker: ^6.1.1
  firebase_core: ^2.9.0
  firebase_storage: ^11.6.7
  fl_chart: ^0.66.2
  flex_color_picker: ^3.2.0
  webviewx_plus: ^0.5.0
  flutter_mobx: ^2.0.0
  flutter_native_splash: ^2.3.2
  flutter_rating_bar: ^4.0.1
  flutter_search_bar: ^3.0.0-dev.1
  flutter_typeahead: ^5.0.2
  flutter_widget_from_html: ^0.14.11
  fwfh_webview: ^0.14.8
  get_it: ^7.2.0
  go_router: ^13.2.0
  google_maps_flutter: ^2.0.1
  image_downloader_web: ^2.0.2
  image_editor_plus: ^1.0.5
  lazy_load_indexed_stack: ^1.1.0
  image_gallery_saver: ^2.0.1
  image_picker: ^1.0.7
  image: ^4.0.15
  intl: ^0.18.0
  jwt_decoder: ^2.0.1
  latlng: ^2.0.7
  lecle_volume_flutter: ^0.0.1+1
  local_auth: ^2.1.6
  mask_text_input_formatter: ^2.4.0
  masked_text: ^1.1.2
  mobx: ^2.0.1
  modal_bottom_sheet: ^3.0.0-pre
  onesignal_flutter: ^5.1.0
  palette_generator: ^0.3.3+2
  path_provider: ^2.0.1
  pdf: ^3.8.4
  percent_indicator: ^4.2.2
  permission_handler: ^11.0.0
  pointycastle: ^3.2.0-rc0
  pretty_qr_code: ^3.2.1
  process: ^5.0.2
  quill_html_editor: ^2.2.8
  screenshot: ^2.1.0
  share_plus: ^7.0.0
  shared_preferences: ^2.0.15
  sqflite: ^2.0.0+3
  story_view: ^0.16.5
  tab_indicator_styler: ^2.0.0
  table_calendar: ^3.0.9
  universal_html: ^2.2.3
  url_launcher: ^6.0.0
  url_strategy: ^0.2.0
  video_player: ^2.1.6
  voice_message_package: ^2.1.4
  # web_ffi: ^0.7.2 
  webview_flutter: ^4.2.1
  widgets_to_image: ^0.0.2

dependency_overrides:
  path: ^1.9.0
  
  image_gallery_saver:
    git:
      url: 'https://github.com/knottx/image_gallery_saver.git'

  image_editor:
    git:
      url: 'https://github.com/jgrubesa-most/flutter_image_editor'
      ref: main
      path: image_editor
      publish_to: none

  image_editor_common:
    git:
      url: 'https://github.com/jgrubesa-most/flutter_image_editor'
      ref: main
      path: image_editor_common
      publish_to: none

  pdfx:
    git:
      url: 'https://github.com/ScerIO/packages.flutter'
      ref: main
      path: packages/pdfx
      publish_to: none

  flutter_staggered_grid_view:
    git:
      url: https://github.com/MehmetKaranlik/flutter_staggered_grid_view
      ref: master

  flutter_secure_storage:
    git:
      url: https://github.com/ThexXTURBOXx/flutter_secure_storage.git
      ref: develop
      path: flutter_secure_storage
      
  flutter_secure_storage_web:
    git:
      url: https://github.com/ThexXTURBOXx/flutter_secure_storage.git
      ref: develop
      path: flutter_secure_storage_web

  share_files_and_screenshot_widgets:
    git:
      url: https://github.com/CsabaConsulting/Share-Files-And-Screenshot-Widgets-Flutter
      ref: master

  flutter_placeholder_textlines:
    git:
      url: https://github.com/totorigolo/flutter_placeholder_textlines
      ref: master
  
  geolocator:
    git:
      url: https://github.com/adrgit10/flutter-geolocator
      ref: main
      path: geolocator

  geocoder:
    git:
      url: https://github.com/nguyenxdat/flutter_geocoder
      ref: master
  
  geoflutterfire:
    git:
      url: https://github.com/EncryptingWolf/GeoFlutterFire
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  mobx_codegen: ^2.0.1+2
  build_runner: ^2.1.2
  recase: ^4.1.0
  lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/criptografia/