import 'package:plugin_pjmei_components/plugin_pjmei_components.dart';

WhiteLabelApp pjmeiWhiteLabelSettingsApp = WhiteLabelApp(
  appName: 'PJMEI',
  descriptionName: '',
  descriptionAboutApp: '',
  appType: AppType.PJMEI,
  sandbox: EnvironmentSettings(
    establishmentId: 'ff4e94d6-912d-4acf-b335-0736ca5a2882',
    companyId: 'd286430b-83cf-4057-8f11-4204411f8b48',
    idSupport: 'SUPPORT1-SAND-0000-0000-00000000PJMEI',
  ),
  production: EnvironmentSettings(
    establishmentId: '7408f412-ca74-47bb-ad02-5ef12de848bd',
    companyId: 'f327226e-709b-4c6a-ab5e-5c4b25e551e1',
    idSupport: 'SUPPORT1-0000-0000-0000-00000000PJMEI',
  ),
  acceptCompany: true,
  acceptIndividual: true,
  companyAccountLimit: 20,
  individualAccountLimit: 1,
  settings: WhiteLabelSettings(
    appName: 'pjmei',
    initialLocation: '/dashboard',
    screens: WhiteLabelScreensRoute(
      openBusiness: '/register/cnpj/start',
      addBusiness: '/register/company/start'
    ),
    optionsModalUser: [
      const ItemModalWidget(
        title: 'Acessar dashboard',
        icon: EvaIcons.personOutline,
        route: '/dashboard',
      ),
      const ItemModalWidget(
        title: 'Configurações do app',
        icon: EvaIcons.settings2Outline,
        route: '/settings',
      ),
      const ItemModalWidget(
        title: 'Segurança e privacidade',
        icon: EvaIcons.lockOutline,
        route: '/security',
      ),
    ],
    optionsModalBusiness: [
      const ItemModalWidget(
        title: 'Acessar gestão da PF',
        icon: EvaIcons.personOutline,
        route: '/dashboard-pf',
      ),
      const ItemModalWidget(
        title: 'Ir para minhas empresas',
        icon: EvaIcons.logOutOutline,
        route: '/dashboard-pj',
      ),
      ItemModalWidget(
        title: 'Editar empresa atual',
        icon: EvaIcons.edit2Outline,
        route: '/empresa/${companySM.company?.id}/perfil/edit',
      ),
    ],
    chatBot: ChatBotOptionsWhiteLabel(),
  ),
  logoMenuMobile: 'assets/images/logo-pjmei.png',
  logoMenuWeb: 'assets/images/logo-pjmei.png',
  logoSplash: 'assets/images/logo-pjmei.png',
  urlSite: 'https://www.pjmei.app/',
  strings: {
    'home_page_top_title': 'Tudo para sua empresa em um só lugar!',
    'home_page_top_subtitle': 'O controle da sua empresa na palma da sua mão!',
    'home_page_bottom_title': 'Por que usar o PJMEI?',
    'home_page_bottom_subtitle': 'Confira algumas vantagens e benefícios do nosso aplicativo para sua empresa.',
  },
  features: [
    ModulePjmei(
      title: 'Abertura de CNPJ',
      description: 'Oferecemos serviço de abertura MEI para você ter seu CNPJ em apenas 48 horas!',
      displayType: 'FUNCTIONALITY_GRID',
      image: {'type': 'ICON', 'value': 'Icons.article_outlined'},
      index: 0,
      params: {},
    ),
    ModulePjmei(
      title: 'Loja virtual',
      description: 'Quem se formaliza como MEI ganha vários privilégios. Descubra quais e quando você pode exigir cada um.',
      displayType: 'FUNCTIONALITY_GRID',
      image: {'type': 'ICON', 'value': 'EvaIcons.shoppingCartOutline'},
      index: 1,
      params: {},
    ),
    ModulePjmei(
      title: 'Materiais educativos',
      description: 'Conteúdos e dicas exclusivas de diferentes áreas para fazer seu negócio decolar.',
      displayType: 'FUNCTIONALITY_GRID',
      image: {'type': 'ICON', 'value': 'EvaIcons.videoOutline'},
      index: 2,
      params: {},
    ),
    ModulePjmei(
      title: 'Benefícios do MEI',
      description: 'Quem se formaliza como MEI ganha vários privilégios. Descubra quais e quando você pode exigir cada um.',
      displayType: 'FUNCTIONALITY_GRID',
      image: {'type': 'ICON', 'value': 'Icons.handshake_outlined'},
      index: 3,
      params: {},
    ),
    ModulePjmei(
      title: 'Emissão de guias DAS',
      description: 'Evite ter seu CNPJ bloqueado ou multas por falta de pagamento.',
      displayType: 'FUNCTIONALITY_GRID',
      image: {'type': 'ICON', 'value': 'Icons.wysiwyg_outlined'},
      index: 4,
      params: {},
    ),
    ModulePjmei(
      title: 'Emissão de notas fiscais',
      description: 'Quem se formaliza como MEI ganha vários privilégios. Descubra quais e quando você pode exigir cada um.',
      displayType: 'FUNCTIONALITY_GRID',
      image: {'type': 'ICON', 'value': 'Icons.view_timeline_outlined'},
      index: 5,
      params: {},
    ),
    ModulePjmei(
      title: 'Declaração anual',
      description: 'Emita declarações e tenha acesso a históricos diretamente da nossa plataforma.',
      displayType: 'FUNCTIONALITY_GRID',
      image: {'type': 'ICON', 'value': 'Icons.event_outlined'},
      index: 6,
      params: {},
    ),
    ModulePjmei(
      title: 'Situação cadastral',
      description: 'Tenha acesso ao seu cartão CNPJ e a todos os dados da sua empresa em um só lugar.',
      displayType: 'FUNCTIONALITY_GRID',
      image: {'type': 'ICON', 'value': 'Icons.app_registration_outlined'},
      index: 7,
      params: {},
    ),
    ModulePjmei(
      title: 'Cartão CNPJ',
      description: 'Tenha acesso ao seu cartão CNPJ e a todos os dados da sua empresa em um só lugar.',
      displayType: 'FUNCTIONALITY_GRID',
      image: {'type': 'ICON', 'value': 'Icons.article_outlined'},
      index: 8,
      params: {},
    ),
    ModulePjmei(
      title: 'Alterações e baixas',
      description: 'Encerre suas atividades como MEI e dê baixa no seu CNPJ pela nossa plataforma.',
      displayType: 'FUNCTIONALITY_GRID',
      image: {'type': 'ICON', 'value': 'Icons.folder_off_outlined'},
      index: 9,
      params: {},
    ),
    ModulePjmei(
      title: 'Documentos',
      description: 'Encerre suas atividades como MEI e dê baixa no seu CNPJ pela nossa plataforma.',
      displayType: 'FUNCTIONALITY_GRID',
      image: {'type': 'ICON', 'value': 'EvaIcons.fileTextOutline'},
      index: 10,
      params: {},
    ),
    ModulePjmei(
      title: 'Finanças',
      description: 'Encerre suas atividades como MEI e dê baixa no seu CNPJ pela nossa plataforma.',
      displayType: 'FUNCTIONALITY_GRID',
      image: {'type': 'ICON', 'value': 'EvaIcons.checkmarkCircleOutline'},
      index: 11,
      params: {},
    ),
    ModulePjmei(
      title: 'Suporte de especialistas',
      description: 'Encerre suas atividades como MEI e dê baixa no seu CNPJ pela nossa plataforma.',
      displayType: 'FUNCTIONALITY_GRID',
      image: {'type': 'ICON', 'value': 'EvaIcons.questionMarkCircleOutline'},
      index: 12,
      params: {},
    ),
  ],
);